### ISSUE TITLE
The Wood Elf Brothers and possibly some other characters are hostile when they shouldn't be

### ISSUE THREAD

**Issue by devinsilver** [ixanza/Equanimity#17]
**Describe the bug**
Just started a new game. Did the things I usually do from the Vanilla Start. Side with Ralof, stay in Gerdur's house until 4 am then go to the mine near Riverwood and kill some bandits. Didn't fully clear it. After that I got the quest for the Golden Claw and made my way to Whiterun and saved and exited before I entered because I wanted to play something else. When I entered Whiterun and then went to the square with the merchants The woodelf that sells meat, Anoriath, the one that is the hunter was hostile to me and wouldn't stop attacking unless I killed him. Thinking this might be connected to his brother I went to the Winking Skeever and his brother was hostile too, but constantly surrendering. Reloaded three times and went to the winking skeever, and both times the wood elf owner was hostile to me but constantly surrendering. One time Acolite Jensen was there too and he was also running away from me. And yes this happens whether or not I fight the Anoriath in the market square. The owner of the winking skeever always cowers before me and I can't interact with him.

**To Reproduce**

Go to whiterun after just starting the game from Riverwood. Go to town square. Boom Anoriath is trying to hunt me.
Go to winking skeever. Owner is cowering before me.

**Expected behavior**
They shouldn't attack me. I just started the game. Didn't do anything

**Modlist version**
3.50
**Did you add any additional mods?**
No

**Comment by ixanza** [comment]
This is a vanilla but, you have a phantom bounty, punch a guard, pay a fine. or use player.paycrimegold

**Comment by Soobrakay** [comment]
Hello!

The workaround does work, but I believe there is some mod interplay or some such that is causing this to occur.

I have thousands of hours in Skyrim across LE, SE, and consoles with and without mods and never had this happen. 

Started using Equanimity and have gotten this to trigger twice, both in Whiterun. Both times as Imperial, one using the Penitus Oculatus start; other time using Vigilant of Stendarr start.

Anoriath and the 4 main NPCs in Dragonsreach all aggro after I do Bleak Falls Barrow to retrieve the Dragonstone.

0 crime or theft, only locks picked in dungeons.

The workaround also affects Wintersun roleplay since punching a guard is an open crime and all the dieties I choose abandon me as a byproduct.

Occurred while using Equanimity 3.5.0 and 3.6.0.1.

**Comment by ThwartAbyss54** [comment]
I have also across all my time playing skyrim only had this happen on this modlist. I find that doing paycrimegold in console and then waiting somewhere for a day clears the aggro and you can progress as normal

**Comment by Soobrakay** [comment]
Ah well. Couldn't reproduce it after those two times so guess bad luck that I had it two playthrough attempts in a row.
