### ISSUE TITLE
Can Not Install

### ISSUE THREAD

**Issue by DragoonPreston** [ixanza/Equanimity#21]
Pack needs to be updated, can not install thew Wabbajack.

**Comment by marcopennekamp** [comment]
If the issue is that Wabbajack cannot download "Better Females Eyebrows", that's because the mod has been set to hidden: https://www.nexusmods.com/skyrimspecialedition/mods/9474

**Workaround:** 

1. Download the mod manually from the Skyrim Nexus: https://www.nexusmods.com/skyrim/mods/50302
2. The ZIP will be named "Better Females Eyebrows-50302-1-2.7z". Rename it to "Better Females Eyebrows-9474-1-2.7z". The different number is just the mod's ID in the SSE Nexus; the mod itself is the same.
3. Move the ZIP file to Equanimity's download folder (where all the other mod ZIPs are located) and restart Wabbajack.

This worked for me. As the mod is the same (and just a texture mod), it should pose no problems. The eyebrows were also available during character creation and worked fine.

I hope this helps. :)

If this isn't the issue, pay attention to the info and error messages inside Wabbajack. If you post relevant errors here, it'll be easier to identify your specific issue.

**Comment by arkthuris** [comment]
The issue for me seems to be that equanimity isn't even listed on Wabbajack at this time.

**Comment by ixanza** [comment]
i've removed this due to not wanting to work on it anymore, it hasn't been supported in a month + and wont be
